#!/bin/bash

echo "=========================================="
echo "   ATLAS Governance Gateway Setup"
echo "=========================================="
echo ""

# Load existing .env if it exists
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi

# 1. Ask for Atlas Brain Location (Modal Function)
DEFAULT_MODAL_FUNC="nislam-mics/ATLAS-NIST-Measure"
PRESENT_MODAL_FUNC=${MODAL_FUNCTION_NAME:-$DEFAULT_MODAL_FUNC}
read -p "Enter the Modal Function Name for the Atlas Brain [current: $PRESENT_MODAL_FUNC]: " MODAL_FUNC
MODAL_FUNC=${MODAL_FUNC:-$PRESENT_MODAL_FUNC}
echo "-> Using Modal Function: $MODAL_FUNC"
echo ""

# 2. Ask for Agent AI Configuration
echo "Choose your Agent AI Backend:"
echo "1) OpenAI (Requires API Key)"
echo "2) Local LLM (Ollama - Free/Private)"
read -p "Select [1/2] (current config remains if skipped): " AI_CHOICE

if [ "$AI_CHOICE" == "1" ]; then
    read -s -p "Enter your OpenAI API Key: " OPENAI_KEY
    echo ""
    AI_ENV_VAR="OPENAI_API_KEY=$OPENAI_KEY"
    echo "-> Configured for OpenAI GPT-4."
elif [ "$AI_CHOICE" == "2" ]; then
    echo "-> Configured for Local LLM (Ollama)."
    echo "   Ensure you have run: ollama pull mistral-nemo"
    AI_ENV_VAR="OPENAI_API_KEY="
else
    # Keep existing if blank
    if [ -n "$OPENAI_API_KEY" ]; then
        AI_ENV_VAR="OPENAI_API_KEY=$OPENAI_API_KEY"
        echo "-> Keeping existing OpenAI Configuration."
    else
        AI_ENV_VAR="OPENAI_API_KEY="
        echo "-> Defaulting to Local LLM (Ollama)."
    fi
fi
echo ""

# 3. Inngest Configuration (Production vs Local)
echo "------------------------------------------"
echo "Inngest Configuration"
echo "------------------------------------------"

if [ -z "$INNGEST_EVENT_KEY" ]; then
    read -p "Enter Inngest Event Key: " INNGEST_EVENT
else
    read -p "Enter Inngest Event Key [current: ****...]: " INNGEST_EVENT
    INNGEST_EVENT=${INNGEST_EVENT:-$INNGEST_EVENT_KEY}
fi

if [ -z "$INNGEST_SIGNING_KEY" ]; then
    read -p "Enter Inngest Signing Key: " INNGEST_SIGNING
else
    read -p "Enter Inngest Signing Key [current: ****...]: " INNGEST_SIGNING
    INNGEST_SIGNING=${INNGEST_SIGNING:-$INNGEST_SIGNING_KEY}
fi

if [ -n "$INNGEST_EVENT" ]; then
    INNGEST_VARS="INNGEST_EVENT_KEY=$INNGEST_EVENT\nINNGEST_SIGNING_KEY=$INNGEST_SIGNING"
    echo "-> Configured for Inngest Cloud."
else
    INNGEST_VARS="# INNGEST_EVENT_KEY=\n# INNGEST_SIGNING_KEY="
    echo "-> No Inngest keys provided. Local Dev mode only."
fi
echo ""

# 4. Modal Credentials
echo "------------------------------------------"
echo "Modal Credentials"
echo "------------------------------------------"

if [ -z "$MODAL_TOKEN_ID" ]; then
    read -p "Enter Modal Token ID: " M_TOKEN_ID
else
    read -p "Enter Modal Token ID [current: $MODAL_TOKEN_ID]: " M_TOKEN_ID
    M_TOKEN_ID=${M_TOKEN_ID:-$MODAL_TOKEN_ID}
fi

if [ -z "$MODAL_TOKEN_SECRET" ]; then
    read -s -p "Enter Modal Token Secret: " M_TOKEN_SECRET
else
    read -s -p "Enter Modal Token Secret [current: ****...]: " M_TOKEN_SECRET
    M_TOKEN_SECRET=${M_TOKEN_SECRET:-$MODAL_TOKEN_SECRET}
fi
echo ""

# 5. Create .env file for Docker
echo "Creating/Updating .env file..."
# Write new config
echo "# Generated by setup.sh" > .env
echo "MODAL_FUNCTION_NAME=$MODAL_FUNC" >> .env
echo "MODAL_TOKEN_ID=$M_TOKEN_ID" >> .env
echo "MODAL_TOKEN_SECRET=$M_TOKEN_SECRET" >> .env
echo "$AI_ENV_VAR" >> .env
echo -e "$INNGEST_VARS" >> .env

echo ".env file updated."
echo ""

# 6. Docker Build & Run
read -p "Do you want to build and run the Docker container now? [y/N]: " RUN_DOCKER
if [[ "$RUN_DOCKER" =~ ^[Yy]$ ]]; then
    echo "Building Docker image..."
    docker build -t atlas-gateway .
    
    echo "Running Docker container..."
    docker run -it --rm -p 8000:8000 --env-file .env atlas-gateway
else
    echo "Setup complete. To run manually:"
    echo "docker run -p 8000:8000 --env-file .env atlas-gateway"
fi
